---
- hosts: cluster
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Instalando o nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes
  handlers:
  - name: Restartando o Nginx
    service:
      name: nginx
      state: restarted
...
